### ISSUE TITLE
No BIP39 lib include

### ISSUE THREAD

**Issue by Willburn** [mhssamadani/Autolykos2_NV_Miner#1]
Compiling in windows with VC 2019 the compile cannot find BIP39 libaries. I solved this by copying the src/bip39 from Autolykos -GPU-miner to the same folde rin Autolykos2_NV_miner. 

However when starting up miner to a node that is synched to network the miner spams every 100ms without any information if the block is getting hashed: 
021-01-04 15:52:39,814 INFO [main thread] Got new block in main thread, block data: {
  "MSG" : "xxx",
  "B" : ,xxx
  "H" : ,xxx
  "PK" : "xxx"

This was main branch with the following commit: https://github.com/mhssamadani/Autolykos2_NV_Miner/commit/e48a7668a22bd7064d7474e76efe06d49e5cb55b

**Comment by amin63moradi** [comment]
solved in #2
