### ISSUE TITLE
1.01 ErgoStratumProxy bug Windows 10

### ISSUE THREAD

**Issue by Willburn** [mhssamadani/Autolykos2_NV_Miner#11]
Starting the proxy it says it cant find module root for bignum/index.js.

"Error: Could not find module root given file: "E:\mining\ergominer\node_modules\bignum\index.js". Do you have a package.json file?"

commit f1608b96ad34314877aea5abe9f620cee920292b

**Comment by JustFragger** [comment]
Same problem.

**Comment by mhssamadani** [comment]
fixed with the new version of stratum proxy v.1.0.3, bundled with the last release of miner
