### ISSUE TITLE
Nanopool: Wrong extranonce

### ISSUE THREAD

**Issue by Soldize** [mhssamadani/Autolykos2_NV_Miner#12]
hello,

How can i fix this in Proxy:

"Oh no! Our work was refused because: Wrong extranonce"

after a couple time:

"Connection closed"

best regards

**Comment by mhssamadani** [comment]
it is something at nanopool side which at this moment I cannot figure out. 
reopening proxy several time is suggested to work by some miners.
Better to use other pools with this miner.

**Comment by Soldize** [comment]
ok, 
which pools are there?

**Comment by mhssamadani** [comment]
there was a mis-config on the nanopool side, which is fixed now.
