### ISSUE TITLE
Error 0xc000007b

### ISSUE THREAD

**Issue by benda95280** [mhssamadani/Autolykos2_NV_Miner#28]
Hello,

No matter what's i'm doing (Compile Myself, or using any release version), i've the following error :

![image](https://user-images.githubusercontent.com/1539408/108569027-7d5ccb80-730b-11eb-8df5-b61f9edf5e11.png)

Any idea ?
Thanks

**Comment by amin63moradi** [comment]
hi, 
this application designed to run on 64-bit operating system and need 64 bit libraries (OpenSSL).

**Comment by benda95280** [comment]
![image](https://user-images.githubusercontent.com/1539408/108592891-9186e400-7370-11eb-876c-9e059d5024c6.png)

![image](https://user-images.githubusercontent.com/1539408/108592901-9f3c6980-7370-11eb-9609-d01f77cbc8ad.png)

It's seems i'm having all requierement ?

**Comment by benda95280** [comment]
Same with lastest version, any help ?

**Comment by benda95280** [comment]
Fixed, wish you the best, and have a nice day.
Thanks.

**Comment by livejamie** [comment]
How did you fix this @benda95280? Having the same issue.

**Comment by FlameSalamander** [comment]
@benda95280 could you share your fix?
