### ISSUE TITLE
 Incomplete config: node or seed are not specified

### ISSUE THREAD

**Issue by CraneCooker** [mhssamadani/Autolykos2_NV_Miner#6]
I set config.json as : { "node": "http://127.0.0.1:9052" }, then start the miner, but it shows:
ERROR [main thread] Incomplete config: node or seed are not specified
do I need add a "seed" in the config.json ?

**Comment by CraneCooker** [comment]
I set the config.json as below then launch the miner :
{
"seed": "<my mnemonic sentences>",
"node": "http://127.0.0.1:9053",
"keepPrehash": false
}
but the miner keeps showing the same info as below, what happen?
2021-01-24 21:29:34,009 INFO [main thread] Waiting for block data to be published by node...
2021-01-24 21:29:34,025 ERROR [main thread] Some of expected fields not present in /block/candidate
2021-01-24 21:29:34,025 ERROR [main thread] Block data: {
  "MSG" : "FF73B7B030790591BA5DEE54543BA36F132FCB12E119EDC12571348C9BD8B8C1",
  "B" : 38631372959920788039535641792206406965033184509028718275260993,
  "PK" : "03E68625862EBD2B98EDAF80ABCB0C0511A14AC9216EB8CAE05E456DC54E65F334"
}
2021-01-24 21:29:34,849 INFO [main thread] Waiting for block data to be published by node...
2021-01-24 21:29:34,861 ERROR [main thread] Some of expected fields not present in /block/candidate
2021-01-24 21:29:34,862 ERROR [main thread] Block data: {
  "MSG" : "FF73B7B030790591BA5DEE54543BA36F132FCB12E119EDC12571348C9BD8B8C1",
  "B" : 38631372959920788039535641792206406965033184509028718275260993,
  "PK" : "03E68625862EBD2B98EDAF80ABCB0C0511A14AC9216EB8CAE05E456DC54E65F334"
}
2021-01-24 21:29:35,663 INFO [main thread] Waiting for block data to be published by node...
2021-01-24 21:29:35,675 ERROR [main thread] Some of expected fields not present in /block/candidate
2021-01-24 21:29:35,676 ERROR [main thread] Block data: {
  "MSG" : "FF73B7B030790591BA5DEE54543BA36F132FCB12E119EDC12571348C9BD8B8C1",
  "B" : 38631372959920788039535641792206406965033184509028718275260993,
  "PK" : "03E68625862EBD2B98EDAF80ABCB0C0511A14AC9216EB8CAE05E456DC54E65F334"
}

**Comment by amin63moradi** [comment]
hi CraneCooker, i think that you use old commit, please get and test the last commit.

**Comment by CraneCooker** [comment]
I git clone the latest commit: git clone https://github.com/mhssamadani/Autolykos2_NV_Miner.git
then compiled a new miner.exe, used below config.json:
{ "node": "http://127.0.0.1:9053" }
and started miner, it shows the same situation.... here is the log:
2021-01-24 22:28:05,196 INFO [main thread] Using 1 GPU devices
2021-01-24 22:28:05,196 INFO [main thread] Using configuration file config0.json
2021-01-24 22:28:05,196 INFO [main thread] Block getting URL:
   http://127.0.0.1:9053/mining/candidate
2021-01-24 22:28:05,212 INFO [main thread] Solution posting URL:
   http://127.0.0.1:9053/mining/solution
2021-01-24 22:28:05,212 ERROR [main thread] Some of expected fields not present in /block/candidate
2021-01-24 22:28:05,212 ERROR [main thread] Block data: {
  "MSG" : "1B743B6A27FBCDFA6FE07CE96CC9741CA53268720E278C4F0B196691F03E46CD",
  "B" : 38631372959920788039535641792206406965033184509028718275260993,
  "PK" : "03E68625862EBD2B98EDAF80ABCB0C0511A14AC9216EB8CAE05E456DC54E65F334"
}
2021-01-24 22:28:05,305 INFO [GPU 0 miner] GPU 0 allocating memory
2021-01-24 22:28:06,029 INFO [main thread] Waiting for block data to be published by node...
2021-01-24 22:28:06,041 ERROR [main thread] Some of expected fields not present in /block/candidate
2021-01-24 22:28:06,041 ERROR [main thread] Block data: {
  "MSG" : "1B743B6A27FBCDFA6FE07CE96CC9741CA53268720E278C4F0B196691F03E46CD",
  "B" : 38631372959920788039535641792206406965033184509028718275260993,
  "PK" : "03E68625862EBD2B98EDAF80ABCB0C0511A14AC9216EB8CAE05E456DC54E65F334"
}
2021-01-24 22:28:06,842 INFO [main thread] Waiting for block data to be published by node...
2021-01-24 22:28:06,853 ERROR [main thread] Some of expected fields not present in /block/candidate
2021-01-24 22:28:06,854 ERROR [main thread] Block data: {
  "MSG" : "1B743B6A27FBCDFA6FE07CE96CC9741CA53268720E278C4F0B196691F03E46CD",
  "B" : 38631372959920788039535641792206406965033184509028718275260993,
  "PK" : "03E68625862EBD2B98EDAF80ABCB0C0511A14AC9216EB8CAE05E456DC54E65F334"
}
2021-01-24 22:28:07,668 INFO [main thread] Waiting for block data to be published by node...
2021-01-24 22:28:07,683 ERROR [main thread] Some of expected fields not present in /block/candidate
2021-01-24 22:28:07,683 ERROR [main thread] Block data: {
  "MSG" : "1B743B6A27FBCDFA6FE07CE96CC9741CA53268720E278C4F0B196691F03E46CD",
  "B" : 38631372959920788039535641792206406965033184509028718275260993,
  "PK" : "03E68625862EBD2B98EDAF80ABCB0C0511A14AC9216EB8CAE05E456DC54E65F334"
}

**Comment by CraneCooker** [comment]
BTW, I'm using ergo-4.0.0.jar, which is released 5 days ago. and this miner is updated 7 days ago, so I guess it has not yet updated to fit ergo-4.0.0?

**Comment by CraneCooker** [comment]
sorry.. I tried 3.7.7 node and it's the same. so I think my miner.exe is not right...here is the winbuild.cmd and compile process, could you help check any wrong ?

#below are winbuild.cmd

SET "OPENSSL_DIR=C:\OpenSSL-Win64"
SET "LIBCURL_DIR=C:\curl"
SET "CUDA_COMPUTE_ARCH=61"
SET "BLOCK_DIM=64"
SET "WORKSPACE=0x400000"
cd src
nvcc -o ../miner.exe -Xcompiler "/std:c++14" -gencode arch=compute_%CUDA_COMPUTE_ARCH%,code=sm_%CUDA_COMPUTE_ARCH%^
 -gencode arch=compute_61,code=compute_61 -DBLOCK_DIM=%BLOCK_DIM% -DNONCES_PER_ITER=%WORKSPACE%^
 -I %OPENSSL_DIR%\include ^
 -I %LIBCURL_DIR%\include ^
 -l %LIBCURL_DIR%\builds\libcurl-vc-x64-release-dll-ipv6-sspi-winssl-obj-lib/libcurl ^
 -l %OPENSSL_DIR%\lib\libeay32 -L %OPENSSL_DIR%/lib ^
 -lnvml ^
conversion.cc cryptography.cc definitions.cc jsmn.c httpapi.cc ^
mining.cu prehash.cu processing.cc request.cc easylogging++.cc autolykos.cu

cd ..
SET PATH=%PATH%;C:\Program Files\NVIDIA Corporation\NVSMI


#below are compile process:

C:\ergo_miner\Autolykos2_NV_Miner\secp256k1>winbuild.cmd
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1>SET "OPENSSL_DIR=C:\OpenSSL-Win64"
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1>SET "LIBCURL_DIR=C:\curl"
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1>SET "CUDA_COMPUTE_ARCH=61"
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1>SET "BLOCK_DIM=64"
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1>SET "WORKSPACE=0x400000"
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1>cd src
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1\src>nvcc -o ../miner.exe -Xcompiler "/std:c++14" -gencode arch=compute_61,code=sm_61 -gencode arch=compute_61,code=compute_61 -DBLOCK_DIM=64 -DNONCES_PER_ITER=0x400000 -I C:\OpenSSL-Win64\include  -I C:\curl\include  -l C:\curl\builds\libcurl-vc-x64-release-dll-ipv6-sspi-winssl-obj-lib/libcurl  -l C:\OpenSSL-Win64\lib\libeay32 -L C:\OpenSSL-Win64/lib  -lnvml conversion.cc cryptography.cc definitions.cc jsmn.c httpapi.cc mining.cu prehash.cu processing.cc request.cc easylogging++.cc autolykos.cu
conversion.cc
cryptography.cc
definitions.cc
jsmn.c
httpapi.cc
mining.cu
prehash.cu
prehash.cu(55): warning: variable "sdata" was declared but never referenced

processing.cc
processing.cc(125): warning C4477: “sprintf”: 格式字符串“%016lX”需要类型“unsigned long”的参数，但可变参数 2 拥有了类型“uint64_t”
processing.cc(125): note: 请考虑在格式字符串中使用“%llX”
processing.cc(125): note: 请考虑在格式字符串中使用“%IX”
processing.cc(125): note: 请考虑在格式字符串中使用“%I64X”
processing.cc(125): warning C4477: “sprintf”: 格式字符串“%016lX”需要类型“unsigned long”的参数，但可变参数 3 拥有了类型“uint64_t”
processing.cc(125): note: 请考虑在格式字符串中使用“%llX”
processing.cc(125): note: 请考虑在格式字符串中使用“%IX”
processing.cc(125): note: 请考虑在格式字符串中使用“%I64X”
processing.cc(125): warning C4477: “sprintf”: 格式字符串“%016lX”需要类型“unsigned long”的参数，但可变参数 4 拥有了类型“uint64_t”
processing.cc(125): note: 请考虑在格式字符串中使用“%llX”
processing.cc(125): note: 请考虑在格式字符串中使用“%IX”
processing.cc(125): note: 请考虑在格式字符串中使用“%I64X”
processing.cc(125): warning C4477: “sprintf”: 格式字符串“%016lX”需要类型“unsigned long”的参数，但可变参数 5 拥有了类型“uint64_t”
processing.cc(125): note: 请考虑在格式字符串中使用“%llX”
processing.cc(125): note: 请考虑在格式字符串中使用“%IX”
processing.cc(125): note: 请考虑在格式字符串中使用“%I64X”
processing.cc(144): warning C4477: “sprintf”: 格式字符串“%016lX”需要类型“unsigned long”的参数，但可变参数 1 拥有了类型“uint64_t”
processing.cc(144): note: 请考虑在格式字符串中使用“%llX”
processing.cc(144): note: 请考虑在格式字符串中使用“%IX”
processing.cc(144): note: 请考虑在格式字符串中使用“%I64X”
processing.cc(144): warning C4477: “sprintf”: 格式字符串“%016lX”需要类型“unsigned long”的参数，但可变参数 2 拥有了类型“uint64_t”
processing.cc(144): note: 请考虑在格式字符串中使用“%llX”
processing.cc(144): note: 请考虑在格式字符串中使用“%IX”
processing.cc(144): note: 请考虑在格式字符串中使用“%I64X”
processing.cc(144): warning C4477: “sprintf”: 格式字符串“%016lX”需要类型“unsigned long”的参数，但可变参数 3 拥有了类型“uint64_t”
processing.cc(144): note: 请考虑在格式字符串中使用“%llX”
processing.cc(144): note: 请考虑在格式字符串中使用“%IX”
processing.cc(144): note: 请考虑在格式字符串中使用“%I64X”
processing.cc(144): warning C4477: “sprintf”: 格式字符串“%016lX”需要类型“unsigned long”的参数，但可变参数 4 拥有了类型“uint64_t”
processing.cc(144): note: 请考虑在格式字符串中使用“%llX”
processing.cc(144): note: 请考虑在格式字符串中使用“%IX”
processing.cc(144): note: 请考虑在格式字符串中使用“%I64X”
processing.cc(144): warning C4477: “sprintf”: 格式字符串“%016lX”需要类型“unsigned long”的参数，但可变参数 5 拥有了类型“uint64_t”
processing.cc(144): note: 请考虑在格式字符串中使用“%llX”
processing.cc(144): note: 请考虑在格式字符串中使用“%IX”
processing.cc(144): note: 请考虑在格式字符串中使用“%I64X”
request.cc
easylogging++.cc
autolykos.cu
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1\include\httplib.h(943): warning: expression has no effect
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1\include\httplib.h(955): warning: expression has no effect
autolykos.cu(66): warning: variable "logstr" was declared but never referenced
autolykos.cu(89): warning: variable "logstr" was declared but never referenced
autolykos.cu(197): warning: variable "ind" was declared but never referenced
autolykos.cu(423): warning: variable "logstr" was declared but never referenced
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1\include\httplib.h(943): warning: expression has no effect
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1\include\httplib.h(955): warning: expression has no effect
  正在创建库 ..\miner.lib 和对象 ..\miner.exp
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1\src>cd ..
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1>SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\libnvvp;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\NetSarang\Xftp 6\;C:\Program Files (x86)\NetSarang\Xshell 6\;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\Nsight Compute 2020.2.0\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx86\x86;c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\vc\Auxiliary\Build\;C:\Users\zheny\AppData\Local\Microsoft\WindowsApps;C:\Users\zheny\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\NVIDIA Corporation\NVSMI;C:\Program Files\NVIDIA Corporation\NVSMI;C:\Program Files\NVIDIA Corporation\NVSMI;C:\Program Files\NVIDIA Corporation\NVSMI;C:\Program Files\NVIDIA Corporation\NVSMI
C:\ergo_miner\Autolykos2_NV_Miner\secp256k1>

**Comment by CraneCooker** [comment]
how to set public key ? each my miner starts, the ergo node error:
00:14:54.835 INFO  [ctor.default-dispatcher-9] o.e.mining.ErgoMiner - Generating new candidate requested by external miner
[ERROR] [01/25/2021 00:14:54.835] [ergoref-akka.actor.default-dispatcher-9] [akka.actor.ActorSystemImpl(ergoref)] Error during processing of request: 'Candidate could not be generated: no public key available'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
java.lang.Exception: Candidate could not be generated: no public key available
        at org.ergoplatform.mining.ErgoMiner.org$ergoplatform$mining$ErgoMiner$$generateCandidate(ErgoMiner.scala:267)
        at org.ergoplatform.mining.ErgoMiner$$anonfun$mining$1.$anonfun$applyOrElse$7(ErgoMiner.scala:295)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1429)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

and my miner config.json is:
{
"seed": "(my mnemonic words)",
"node": "http://127.0.0.1:9053",
"keepPrehash": false
}

the ergo node ergo.conf is:
ergo {
    directory = "c:/ergo"
    node {
        mining = true
        useExternalMiner=true
    }
    wallet.secretStorage.secretDir = "c:/ergo"
}
scorex {
    restApi {
        # Hex-encoded Blake2b256 hash of an API key. 
        # Should be 64-chars long Base16 string.
        # below is the hash of the string 'hello'
        # replace with your actual hash 
        apiKeyHash = "b***58"
    }
}

**Comment by mhssamadani** [comment]
This tutorial is not valid in the incoming fork (current miner and node v4): https://github.com/ergoplatform/ergo/wiki/Mining-Ergo-for-Fun-and-Profit
Also, in the config file you should only have {"node":"address"} and nothing more.
Also, you can only mine on testnet with this miner right now, since the fork is not happened yet.

**Comment by CraneCooker** [comment]
it's clear, thank you.
looking forwards to new update
