### ISSUE TITLE
Low diff share

### ISSUE THREAD

**Issue by neal-zhu** [mhssamadani/Autolykos2_NV_Miner#9]
Hi there,

  We are developing a mining pool. When we test this miner with stratum proxy(connected to our pool), our pool got a lot of low diff share(almost half of all shares).
  Could you please take a look at this submit:
```
msg = "bf98bfe7e3e36512825e9f490012c10cb89333c484cc87de634a2690e4a11677"
nonce = "0000AAAADAA2444C"
height = 5398
```
Our pool target is
```
578960446186580977117854925043439539266349923328202820197287920039565
```
while our solution verify output the target of the solution is 
```
86657639212501117679482563223058298343115354588511047061251764041445060235509
```
way much smaller than target

**Comment by mhssamadani** [comment]
fixed in commit ttps://github.com/mhssamadani/Autolykos2_NV_Miner/commit/f1608b96ad34314877aea5abe9f620cee920292b
please verify
